# Generated by Django 5.2.8 on 2026-01-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='camas',
            field=models.IntegerField(default=0),
        ),
    ]
