# Generated by Django 5.2.8 on 2026-01-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmi', '0002_hospital_camas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={},
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='camas',
            new_name='capacidad_camas',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='fecha_registro',
        ),
        migrations.AlterModelTable(
            name='hospital',
            table=None,
        ),
    ]
