# Generated by Django 5.2.8 on 2026-02-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmi', '0003_alter_hospital_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='nivel',
            field=models.IntegerField(choices=[(1, '1er Nivel'), (2, '2do Nivel'), (3, '3er Nivel')], default=1),
        ),
    ]
