# Generated by Django 5.2.8 on 2026-01-16 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmi', '0003_alter_hospital_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuarto', models.CharField(max_length=10, verbose_name='Nro de Cuarto')),
                ('piso', models.CharField(max_length=50)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuartos', to='superadmi.especialidad')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuartos', to='superadmi.hospital')),
            ],
            options={
                'verbose_name': 'Cuarto',
                'verbose_name_plural': 'Cuartos',
                'unique_together': {('hospital', 'numero_cuarto')},
            },
        ),
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Código/Nro de Cama')),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado'), ('MANTENIMIENTO', 'Mantenimiento')], default='LIBRE', max_length=20)),
                ('cuarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camas', to='hospital.cuarto')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cama_asignada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente_actual', to='hospital.cama')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='superadmi.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='EvolucionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MEDICA', 'Nota del Doctor'), ('ENFERMERIA', 'Nota de Enfermería')], max_length=20)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('presion_arterial', models.CharField(blank=True, max_length=20, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='hospital.paciente')),
            ],
        ),
    ]
