# Generated by Django 5.2.8 on 2026-01-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucionmedica',
            name='descripcion',
            field=models.TextField(verbose_name='Observaciones Médicas'),
        ),
        migrations.AlterField(
            model_name='evolucionmedica',
            name='frecuencia_cardiaca',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evolucionmedica',
            name='indicaciones',
            field=models.TextField(default=35.6, verbose_name='Indicaciones/Tratamiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evolucionmedica',
            name='presion_arterial',
            field=models.CharField(default='0/0', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evolucionmedica',
            name='temperatura',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evolucionmedica',
            name='tipo',
            field=models.CharField(choices=[('RUTINA', 'Revisión de Rutina'), ('URGENCIA', 'Urgencia/Emergencia'), ('ALTA', 'Nota de Alta Médica')], default='RUTINA', max_length=20),
        ),
    ]
