# Generated by Django 5.2.8 on 2026-01-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_evolucionmedica_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('INTERNADO', 'Internado'), ('ALTA', 'De Alta')], default='INTERNADO', max_length=20),
        ),
    ]
