# Generated by Django 5.2.8 on 2026-01-28 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_paciente_estado'),
        ('superadmi', '0003_alter_hospital_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cama',
            name='estado',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado'), ('MANTENIMIENTO', 'Mantenimiento'), ('LIMPIEZA', 'En Limpieza'), ('RESERVADO', 'Reservado')], default='LIBRE', max_length=20),
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Urgencia')], default='MEDIA', max_length=10)),
                ('motivo_traslado', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'En Camino'), ('RECIBIDO', 'Recibido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('hospital_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='superadmi.hospital')),
                ('hospital_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='superadmi.hospital')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.paciente')),
            ],
        ),
    ]
