# Generated by Django 5.2.8 on 2026-03-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_especialidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Especialidad',
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(default='Ninguna'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='motivo_ingreso',
            field=models.TextField(default='', verbose_name='Diagnóstico Presuntivo / Motivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='presion_arterial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='saturacion_oxigeno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='cama',
            name='estado',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado'), ('MANTENIMIENTO', 'Mantenimiento'), ('LIMPIEZA', 'En Limpieza')], default='LIBRE', max_length=20),
        ),
    ]
