# Generated by Django 5.2.8 on 2026-03-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_paciente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
