# Generated by Django 5.2.8 on 2026-03-11 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_paciente_fecha_entrada'),
        ('superadmi', '0005_alter_usuario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivacion',
            name='prioridad',
            field=models.CharField(default='MEDIA', max_length=10),
        ),
        migrations.CreateModel(
            name='Ambulancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('BÁSICA', 'Básica'), ('AVANZADA', 'Avanzada')], default='BÁSICA', max_length=20)),
                ('estado', models.CharField(default='DISPONIBLE', max_length=20)),
                ('chofer_asignado', models.OneToOneField(blank=True, limit_choices_to={'rol': 'chofer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulancias', to='superadmi.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='derivacion',
            name='ambulancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.ambulancia'),
        ),
    ]
