# Generated by Django 5.2.8 on 2026-03-13 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_derivacion_prioridad_ambulancia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambulancia',
            options={'verbose_name': 'Ambulancia', 'verbose_name_plural': 'Ambulancias'},
        ),
        migrations.AlterModelOptions(
            name='derivacion',
            options={'verbose_name': 'Derivación', 'verbose_name_plural': 'Derivaciones'},
        ),
        migrations.AddField(
            model_name='cama',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cama',
            name='prioridad',
            field=models.CharField(choices=[('ESTABLE', 'Estable'), ('URGENTE', 'Urgente'), ('CRITICO', 'Crítico')], default='ESTABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ambulancia',
            name='chofer_asignado',
            field=models.OneToOneField(blank=True, limit_choices_to={'rol__nombre': 'chofer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulancia_personal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ambulancia',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_CAMINO', 'En Camino / Traslado'), ('MANTENIMIENTO', 'En Mantenimiento')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cama',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='derivacion',
            name='ambulancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones', to='hospital.ambulancia'),
        ),
        migrations.AlterField(
            model_name='derivacion',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRÍTICA', 'Crítica')], default='MEDIA', max_length=10),
        ),
    ]
