# Generated by Django 5.2.8 on 2026-03-25 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_ambulancia_options_alter_derivacion_options_and_more'),
        ('superadmi', '0005_alter_usuario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='derivacion',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ContrarreferenciaD7a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('resumen_egreso', models.TextField()),
                ('hallazgos_relevantes', models.TextField()),
                ('tratamiento_recomendado', models.TextField()),
                ('conducta_a_seguir', models.TextField()),
                ('hospital_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_destino', to='superadmi.hospital')),
                ('hospital_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_origen', to='superadmi.hospital')),
                ('medico_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.paciente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenciaD7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('resumen_anamnesis', models.TextField()),
                ('examen_fisico', models.TextField()),
                ('diagnostico_cie10', models.CharField(max_length=10)),
                ('motivo_referencia', models.CharField(max_length=200)),
                ('tratamiento_realizado', models.TextField()),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('hospital_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_destino', to='superadmi.hospital')),
                ('hospital_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_origen', to='superadmi.hospital')),
                ('medico_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.paciente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransferenciaD7b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('servicio_origen', models.CharField(max_length=100)),
                ('servicio_destino', models.CharField(max_length=100)),
                ('resumen_clinico', models.TextField()),
                ('riesgo_traslado', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], max_length=50)),
                ('hospital_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_destino', to='superadmi.hospital')),
                ('hospital_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_origen', to='superadmi.hospital')),
                ('medico_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.paciente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
