# Generated by Django 5.2.8 on 2026-03-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_derivacion_creado_por_contrarreferenciad7a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioD7b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eess_transfiere', models.CharField(blank=True, max_length=200, null=True)),
                ('nivel_eess', models.CharField(blank=True, max_length=50, null=True)),
                ('red_salud', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('hc', models.CharField(blank=True, max_length=50, null=True)),
                ('procedencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fc', models.CharField(blank=True, max_length=20, null=True)),
                ('fr', models.CharField(blank=True, max_length=20, null=True)),
                ('pa', models.CharField(blank=True, max_length=20, null=True)),
                ('temp', models.CharField(blank=True, max_length=20, null=True)),
                ('peso', models.CharField(blank=True, max_length=20, null=True)),
                ('glasgow', models.CharField(blank=True, max_length=20, null=True)),
                ('spo2', models.CharField(blank=True, max_length=20, null=True)),
                ('anamnesis', models.TextField(blank=True, null=True)),
                ('diag_a', models.CharField(blank=True, max_length=255, null=True)),
                ('cie_a', models.CharField(blank=True, max_length=10, null=True)),
                ('diag_b', models.CharField(blank=True, max_length=255, null=True)),
                ('cie_b', models.CharField(blank=True, max_length=10, null=True)),
                ('cons_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('cons_edad', models.CharField(blank=True, max_length=10, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_d7b', to='hospital.paciente')),
            ],
        ),
        migrations.DeleteModel(
            name='TransferenciaD7b',
        ),
    ]
