# Generated by Django 5.2.8 on 2026-03-25 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_formulariod7b_delete_transferenciad7b'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioD7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eess_solicitante', models.CharField(blank=True, max_length=200, null=True)),
                ('eess_receptor', models.CharField(blank=True, max_length=200, null=True)),
                ('especialidad_solicitada', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_referencia', models.DateField(auto_now_add=True)),
                ('motivo_referencia', models.TextField(blank=True, null=True)),
                ('examen_fisico', models.TextField(blank=True, null=True)),
                ('diagnostico_presuntivo', models.CharField(blank=True, max_length=255, null=True)),
                ('cie_10', models.CharField(blank=True, max_length=10, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_d7', to='hospital.paciente')),
            ],
        ),
        migrations.DeleteModel(
            name='ReferenciaD7',
        ),
    ]
