# Generated by Django 5.2.8 on 2026-03-30 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_formulariod7_delete_referenciad7'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrarreferenciad7a',
            name='conducta_a_seguir',
        ),
        migrations.RemoveField(
            model_name='contrarreferenciad7a',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='contrarreferenciad7a',
            name='hallazgos_relevantes',
        ),
        migrations.RemoveField(
            model_name='contrarreferenciad7a',
            name='hospital_destino',
        ),
        migrations.RemoveField(
            model_name='contrarreferenciad7a',
            name='hospital_origen',
        ),
        migrations.RemoveField(
            model_name='contrarreferenciad7a',
            name='medico_responsable',
        ),
        migrations.RemoveField(
            model_name='contrarreferenciad7a',
            name='resumen_egreso',
        ),
        migrations.RemoveField(
            model_name='contrarreferenciad7a',
            name='tratamiento_recomendado',
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='anexos_pendientes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='cie10_egreso_a',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='cie10_ingreso_a',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='contacto_recibe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='diag_egreso_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='diag_ingreso_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='dias_internacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='discapacidad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='eess_contrarrefiere',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='eess_destino',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='evolucion_complicaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='examenes_complementarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='fc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='fr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='grado_discapacidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='imc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='nivel_eess',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='nombre_acompanante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='observaciones_contrarreferencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='otros_examenes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='pa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='peso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='recomendaciones_paciente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='red_salud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='servicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='spo2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='temperatura',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='tipo_discapacidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrarreferenciad7a',
            name='tratamientos_realizados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ambulancia_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.ambulancia'),
        ),
        migrations.AlterField(
            model_name='contrarreferenciad7a',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_d7a', to='hospital.paciente'),
        ),
    ]
