# Generated by Django 5.2.8 on 2026-04-01 15:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_remove_contrarreferenciad7a_conducta_a_seguir_and_more'),
        ('superadmi', '0005_alter_usuario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('turno', models.CharField(choices=[('MAÑANA', 'Mañana (08:00 - 14:00)'), ('TARDE', 'Tarde (14:00 - 20:00)'), ('NOCHE', 'Noche (20:00 - 08:00)')], max_length=10)),
                ('medico_guardia', models.CharField(max_length=150)),
                ('enfermera_turno', models.CharField(max_length=150)),
                ('chofer_ambulancia', models.CharField(blank=True, max_length=150, null=True)),
                ('camas_cirugia', models.IntegerField(default=0)),
                ('camas_traumatologia', models.IntegerField(default=0)),
                ('camas_medicina_interna', models.IntegerField(default=0)),
                ('camas_pediatria', models.IntegerField(default=0)),
                ('camas_uti', models.IntegerField(default=0)),
                ('camas_neonatologia', models.IntegerField(default=0)),
                ('ambulancias_operativas', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_diarios', to='superadmi.hospital')),
            ],
            options={
                'unique_together': {('hospital', 'fecha', 'turno')},
            },
        ),
    ]
