# Generated by Django 5.2.8 on 2026-04-01 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_reportediario'),
        ('superadmi', '0005_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportediario',
            options={'verbose_name': 'Reporte Diario', 'verbose_name_plural': 'Reportes Diarios'},
        ),
        migrations.AlterUniqueTogether(
            name='reportediario',
            unique_together={('hospital', 'fecha')},
        ),
        migrations.AddField(
            model_name='reportediario',
            name='amb_t1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='amb_t1_op',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='amb_t2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='amb_t2_op',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='auxiliar_manana',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='auxiliar_noche',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='auxiliar_tarde',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='chofer_a',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='chofer_b',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='cir_l',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='cir_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='cir_v',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='cruem_auxiliar',
            field=models.CharField(default='LIC. MARLENE FLORES DELGADO', max_length=150),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='cruem_medico',
            field=models.CharField(default='DRA. ALEJANDRA ABAJO', max_length=150),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='infectologia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='maternidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='med_l',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='med_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='med_v',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='medico_manana',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='medico_noche',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='medico_tarde',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='neo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='ped_camas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='ped_cunas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='personal_reporta',
            field=models.CharField(default='Sistema', help_text='Nombre de quien llena el form', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportediario',
            name='terapia_intermedia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='tra_l',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='tra_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='tra_v',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='uti',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='reportediario',
            name='ambulancias_operativas',
        ),
        migrations.RemoveField(
            model_name='reportediario',
            name='camas_cirugia',
        ),
        migrations.RemoveField(
            model_name='reportediario',
            name='camas_medicina_interna',
        ),
        migrations.RemoveField(
            model_name='reportediario',
            name='camas_neonatologia',
        ),
        migrations.RemoveField(
            model_name='reportediario',
            name='camas_pediatria',
        ),
        migrations.RemoveField(
            model_name='reportediario',
            name='camas_traumatologia',
        ),
        migrations.RemoveField(
            model_name='reportediario',
            name='camas_uti',
        ),
        migrations.RemoveField(
            model_name='reportediario',
            name='chofer_ambulancia',
        ),
        migrations.RemoveField(
            model_name='reportediario',
            name='enfermera_turno',
        ),
        migrations.RemoveField(
            model_name='reportediario',
            name='medico_guardia',
        ),
        migrations.RemoveField(
            model_name='reportediario',
            name='turno',
        ),
    ]
