# Generated by Django 5.2.8 on 2026-04-02 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_alter_reportediario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaCRUEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_incidente', models.CharField(max_length=20, verbose_name='N° Incidente')),
                ('fecha', models.DateField()),
                ('hora_apertura', models.TimeField()),
                ('hora_finalizacion', models.TimeField(blank=True, null=True)),
                ('reportante', models.CharField(max_length=150)),
                ('telefono_celular', models.CharField(max_length=20)),
                ('del_paciente', models.CharField(max_length=150)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('motivo_llamada', models.TextField()),
                ('prioridad', models.CharField(max_length=50)),
                ('respuesta', models.CharField(max_length=100)),
                ('coordinacion_traslado', models.TextField(blank=True, null=True)),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra')),
            ],
        ),
    ]
