# Generated by Django 5.2.8 on 2026-04-13 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_incidenciacruem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancia',
            name='nombre_chofer_manual',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Completo del Chofer'),
        ),
        migrations.AddField(
            model_name='incidenciacruem',
            name='tipo',
            field=models.CharField(choices=[('PRE', 'Prehospitalaria'), ('TRA', 'Traslado'), ('REF', 'Referencia'), ('EVE', 'Evento Deportivo')], default='PRE', max_length=3),
        ),
        migrations.AlterField(
            model_name='ambulancia',
            name='chofer_asignado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulancia_personal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ambulancia',
            name='tipo',
            field=models.CharField(choices=[('BÁSICA', 'Básica'), ('AVANZADA', 'Avanzada'), ('TERAPIA', 'Terapia Intensiva')], default='BÁSICA', max_length=20),
        ),
    ]
