# Generated by Django 5.2.8 on 2026-04-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_ambulancia_nombre_chofer_manual_incidenciacruem_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnfermedadCIE10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=10, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Enfermedad CIE-10',
                'verbose_name_plural': 'Enfermedades CIE-10',
            },
        ),
    ]
