# Generated by Django 5.2.8 on 2026-05-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_enfermedadcie10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuarto',
            name='numero_cuarto',
            field=models.CharField(max_length=50, verbose_name='Nro de Cuarto'),
        ),
    ]
